### ISSUE TITLE
Code Review 4 July

### ISSUE THREAD

**Issue by misterrodger** [fac-17/week-1-EFGH-project#49]
## Great job, everyone!  

* Nice responsive site with 3 screen sizes (thank you!)
* Cool font and colour scheme
* Email submission seems to be working, cool
* Nice profile photo frames
* Github workflow is _tight_  :champagne: 
* HTML headers and semantic HTML are very good  (some people notice these things!)

### Some things that could be done, with remaining time:

* Could add a 'home' button to the NavBar, I think people expect that, in addition to the logo linking to home as well.
* Team section alignment is a bit to the left and layout in general works slightly better on mobile.  Could give desktop some more love.
* One broken LinkedIn link and one pic in readme not showing
* Can we have at least a screenshot or two in the readme?  Bonus: learn how to size them.  I usually use something like ``` <img src="whatever" width=x height=x> ```  in the readme for this.
* Form colours are quite different from the rest of the site.  Also accessibility currently a 92... due to contrast/colours.  Double-check this, you might play around with 0to255.com for help.
Could add hover effect to social media account links as well.
* Could add an icon: ``` <link rel="icon" href="favicon.ico" /> ```
* Could add a footer
* You can add a 'stretch goals' section to the readme

### Question about theme/concept
* What does Koodi mean?  Maybe make that clear (if it even means anything)

### In the code:
* A bit of commented code that should generally be deleted for code review
* I would add line limit of about 80 characters, and use Prettier to clean up formatting and make it more readable.  Sorry if I was unclear about that, I meant that in certain long forms it can be more readable not to use it, so I turn off the "format on save", but in general it is good to use it.

* a couple more optional HTML meta tags that are good to use for SEO purposes:
``` 
<meta name="keywords" content="koodi, web, design, agency, names, etc" />
<meta name="author" content="your names or koodi" /> 
```

### Stretch goals:  
* Form validation, at least in HTML?  You can google and find good regex to put in there, or write your own :muscle: 
* Site seems to have 2 bylines (Let's make things... and Thoughtfully crafted...).  I might think about putting the title/name of the agency there with one of the bylines beneath it, and then either putting a different logo in top/left of Header, or else hide/show the current logo when the Title has scrolled a certain distance.  Might not have time remaining for this right now though.

All in all very well-done, bravo!  :+1:

**Comment by gminova** [comment]
Thank you for the detailed feedback!!

**Comment by jackbridger** [comment]
Yes thank you John this is extremely helpful for us!

**Comment by mkatenolan** [comment]
Thanks John! Really useful feedback!
